### ISSUE TITLE
Bug: Missing method

### ISSUE THREAD

**Issue by rnowling-memphis** [memphisdev/memphis.py#153]
@idanasulinmemphis This line tries to call the `get_broker_manager_connection()` method on the `Memphis` class.  That method doesn't exist, however.  This broke the Python SDK.  It looks like it was added about two weeks ago.

https://github.com/memphisdev/memphis.py/blame/7458b6feafab95facc38f0258f8033c1d7973c66/memphis/memphis.py#L171

**Comment by rnowling-memphis** [comment]
I ran pylint and it caught the error:

memphis/memphis.py:171:40: E1101: Instance of 'Memphis' has no 'get_broker_manager_connection' member (no-member)

I can help with setting up GitHub actions to do some basic CI (build / install package, run pylint) if needed.

**Comment by idanasulinmemphis** [comment]
Thanks @rnowling-memphis, It was accidentally deleted in the last commits. Anyway, I've pushed it back
