### ISSUE TITLE
Raise MemphisSchemaError rather then MemphisError

### ISSUE THREAD

**Issue by rnowling-memphis** [memphisdev/memphis.py#161]
The SDK should probably return a MemphisSchemaError than a generic MemphisError here:

https://github.com/memphisdev/memphis.py/blob/97c0c148d9d0e1778913c2a827219da7e91ced77/memphis/producer.py#L273

**Comment by idanasulinmemphis** [comment]
This has been fixed and will be released on the next version of the SDK
