### ISSUE TITLE
Add documentation to pypi

### ISSUE THREAD

**Issue by SvetaMemphis** [memphisdev/memphis.py#32]

**Comment by SvetaMemphis** [comment]
We need to add to our [setup.py](https://github.com/memphisdev/memphis.py/blob/master/setup.py) **long_description**.
That can be a reference to the description file ([examples here](https://stackoverflow.com/questions/26737222/how-to-make-pypi-description-markdown-work)) or to add a text in the file - take [numpy for example](https://github.com/numpy/numpy/blob/main/setup.py).

The text should be memphis decription as it is written in our [README](https://github.com/memphisdev/memphis.py/edit/master/README.md) from line 26.

**Comment by Adarsh-jaiss** [comment]
-- so, in simple terms, we need to add multi line comments in setup.py file!

**Comment by SvetaMemphis** [comment]
@Adarsh-jaiss Yes, you're right! And there is always the option to refer to a file and then manage the changes in this file. 
We will appreciate a contribution on this one, so our PyPi users will see the documentation as well!

**Comment by Adarsh-jaiss** [comment]
-- can you explain how can i do these things because I am little confused :)

**Comment by Adarsh-jaiss** [comment]
- okay so the thing is i need to update this code syntax in ![setup.py](https://github.com/memphisdev/memphis.py/blob/master/setup.py) and link the ![readme.md](https://github.com/memphisdev/memphis.py/blob/master/README.md) file to it!

```
from setuptools import setup

# read the contents of your README file
from pathlib import Path
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

setup(
    name='an_example_package',
    # other arguments omitted
    long_description=long_description,
    long_description_content_type='text/markdown'
)

```




and kindly review this :

```
from setuptools import setup

# read the contents of your README file
from pathlib import Path
this_directory = Path(__memphis.py/README.md__).parent
long_description = (this_directory / "README.md").read_text()

setup(
    name='pypi',
    # other arguments omitted
    long_description=long_description,
    long_description_content_type='text/markdown'
)

```

-- And here ,please choose one that i need to add in long_description_content type

 ```  
1.  long_description_content_type =  text/markdown; charset=UTF-8; variant=GFM

2.   long_description_content_type='text/markdown'
```
other than that please tell me what to write in ```long_description``` 

and do  i have to replace and add this whole syntax from ![setup.py](https://github.com/memphisdev/memphis.py/blob/master/setup.py) file or i have to just  add this syntax to that file ?

**Comment by SvetaMemphis** [comment]
Thanks for the reply, I think adding these 2 lines will work, this file and README are in the same directory, 

```
setup(
    long_description = file: README.md
    long_description_content_type = text/markdown; charset=UTF-8; variant=GF
)
```

We just need to ensure that our README.md is written according to [PyPa requirements](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/).

you can open a new branch and create a PR :)

**Comment by SvetaMemphis** [comment]
Also here is a good example:
The Repo is [here](https://github.com/pyscaffold/pyscaffoldext-markdown) 
And that's [how it looks in PyPi ](https://pypi.org/project/pyscaffoldext-markdown/)

**Comment by Adarsh-jaiss** [comment]
- please review this, should I make a pr with these changes?

![Annotation 2022-08-26 104202](https://user-images.githubusercontent.com/96974600/186827126-84ca1b1d-744a-497d-9795-0ac13ab88d7f.png)

**Comment by SvetaMemphis** [comment]
Thank you @Adarsh-jaiss for the contribution, it looks good!
Your PR will be merged during the next day and will be released on our next release.
Great having you with us :)

**Comment by Adarsh-jaiss** [comment]
-- Thank you so much @SvetaMemphis for helping me in this whole contribution journey

-- I am in love with the Memphis community and I am looking forward for more such contributions

**Comment by idanasulinmemphis** [comment]
PR approved and will be released on the coming version, thanks a lot @Adarsh-jaiss you are rocking
